development:
  adapter: postgresql
  encoding: unicode
  database: rails
  pool: 5
  username: root
  password: root
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: rails
  pool: 5
  username: root
  password: root
  host: localhost
  port: 5432
  
production:
  adapter: postgresql
  encoding: unicode
  database: rails
  pool: 5
  username: root
  password: root
  host: localhost
  port: 5432